"""
@Author:xiayifan
@Function:该模块定义了神经网络的基本参数
"""
# 参数定义
NUM_OF_INPUT = 4
NUM_OF_HIDDEN = 5
NUM_OF_OUTPUT = 5
LEARNING_RATE = 0.5
CORRECT_RATE = 0.1
RANGE_UNDER = -2
RANGE_UPDER = 2
SIGMOID_WEIGH = 1
RANDOM_WEIGHT = 0.5
RANDOM_BIAS = 0.1
MAX_TIME = 10000
FINAL_ERROR = 0.65*10**(-3)
