'''
遗传算法中参数进行描述
'''
POP_SELECT_SIZE = 60
POP_SIZE = 10  # 种群大小
PROBABILITY_CROSSOVER = 0.4  # 发生染色体交换的概率
PROBABILITY_CROSSOVER_SELECTION = 0.4
PROBABILITY_MUTATION = 0.6  # 发生基因突变的概率
MAX_GENARATION = 20  # 最大繁殖代数
PROBABILITY_STEADY = 0.5  # 稳态繁殖的子代取代父代的概率 Steady Stale Reproduction
SOURCE_NODE = 11
DST_NODE = 9


WIDTH_BIAS = 0
WIDTH_UP = 460000
WIDTH_DOWN = 80000


PACKET_UP = 0.01
PACKET_DOWN = 0